{% set name = "terracotta" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bc0437a15dc5a1bde3be290523459a7ab56aab5588e0daa6bfa08e49efe845f

build:
  number: 2
  entry_points:
    - terracotta=terracotta.scripts.cli:entrypoint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - numpy >=1.15,!=1.17.0
    - pip
    - setuptools_scm_git_archive
    - python
  run:
    - apispec
    - apispec-webframeworks
    - cachetools >=3.1.0
    - click
    - click-spinner
    - flask
    - flask_cors
    - marshmallow >=3.0.0
    - mercantile
    - numpy >=1.15,!=1.17.0
    - pillow
    - python
    - pyyaml >=3.10
    - rasterio >=1.0
    - shapely
    - toml
    - tqdm

test:
  imports:
    - terracotta
    - terracotta.client
    - terracotta.cmaps
    - terracotta.drivers
    - terracotta.handlers
    - terracotta.scripts
    - terracotta.server
  commands:
    - terracotta --help

about:
  home: https://github.com/DHI-GRAS/terracotta
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modern XYZ tile server written in Python
  description: Terracotta is a pure Python tile server that runs as a WSGI app on a dedicated webserver or as a serverless app on AWS Lambda. It is built on a modern Python 3.6 stack, powered by awesome open-source software such as Flask, Zappa, and Rasterio.
  doc_url: https://pypi.org/project/terracotta/#description
  dev_url: https://github.com/DHI-GRAS/terracotta

extra:
  recipe-maintainers:
    - mxr-conda
    - bubblyorca
